### ISSUE TITLE
Can you provide the detailed results on noisy COCO?

### ISSUE THREAD

**Issue by leolee99** [naver-ai/pcmepp#2]
Hi! Thanks for your excellent work. I'd like to compare with some baselines trained on noisy COCO set and cite the results in Table 2. But only average R@1 performances of COCO 1K and 5K are reported. Can you provide more detailed R@K performance on both i2t and t2i? 

Sincerely thanks for your help!

**Comment by SanghyukChun** [comment]
Hi, thanks for your interest! I am now working on rechecking all the experiments in the paper, and some numbers will be updated. It would take about 2-3 days. If you need the numbers immediately, let me check Table 2 first.

**Comment by leolee99** [comment]
Thanks for your help! I only need the result numbers.

**Comment by SanghyukChun** [comment]
@leolee99 
Hello, thanks for your patience
I made a spreadsheet to show the full numbers. (it is still under update)
(See Noisy Correspondence (avg) for your request)
Feel free to ask me anything if you have any follow-up questions
https://docs.google.com/spreadsheets/d/1EMbp03uD7X5puN80zV2wr43Z2FWC4wQ9bo8HXcyU27k/edit?usp=sharing

**Comment by leolee99** [comment]
Thanks for the kind author and your excellent work!
