### ISSUE TITLE
Config file for VSE_infty with ViT-L/14

### ISSUE THREAD

**Issue by jinhyunj** [naver-ai/pcmepp#8]
Hi, thanks for the great work!
I'm doing an experiment with your code and want to know the exact configuration for the results of VSE_infty with ViT-L/14 backbone.
Could you please provide the corresponding config file?
Thank you!

**Comment by SanghyukChun** [comment]
It does not need a new configuration file. The following command will work (for 8 GPUs)
```
python3 train.py ./configs/others/vse_infty.yaml --dataloader__data_path /path/to/dataset --model__backbone_source clip_ViT-L/14 --model__img_dim 1024 --dataloader__batch_size 16 --train__all_gather 1
```
